### ISSUE TITLE
Missing name in "Better Court Mage"

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#105]
**Repro Steps**
1. Have a court mage.
2. Get another mage in your court that would be a better court mage.
3. Get the event where the new mage wants to replace the court mage.

**Actual**
The descriptive text mentions "<new mage> claims that she would be a better Court Mage than , and petitions".  Notice that there is a space after "than".

**Expected**
That the name of the existing Court Mage appear after the word "than".

**Notes**
Not sure if this is consistently reproducible.  My existing court mage did not have an unusual name as far as I know.

![bug22_better-court-mage](https://user-images.githubusercontent.com/39809872/42128450-edaf08c0-7c79-11e8-880a-d6130da8b89d.png)

**Comment by TerryDuke** [comment]
At first glance it seems okay:

EVTDESCcourt.21;[From.GetBestName] claims that [From.GetSheHe] would be a better Court Mage than [Root.job_mage.GetTitledFirstName], and petitions that [From.GetSheHe] should be given the title of Court Mage of the [Root.PrimaryTitle.GetFullName].;;;;;;;;;;;;;x

compared with

EVTDESCcourt.71;[From.GetBestName] claims that [From.GetSheHe] would be a better Steward than [Root.job_treasurer.GetTitledFirstName], and petitions that [From.GetSheHe] should be given the title of Steward of the [Root.PrimaryTitle.GetFullName].;;;;;;;;;;;;;x

The variable "job_mage" seems defined the same way as job_chancellor and the others, as well.  Will keep looking.

**Comment by rquinio** [comment]
I've reworked the localization text to avoid direct usage of job_mage.
