### ISSUE TITLE
Druid cures me even though I'm not ill

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#106]
**Repro Steps**
1. Get the event where a druid (in your court?) visits you and cures your fever.

**Expected**
That I only get this event when I'm ill.

**Actual**
I was not ill, and I still got this event. The "Alive!" option also informs me that I'm no longer ill.

![bug23_not_ill_druid](https://user-images.githubusercontent.com/39809872/42128485-b4c19da6-7c7a-11e8-9c1d-5d7ae6c3061b.png)

**Comment by TerryDuke** [comment]
There's some confusion between "is_ill" and "trait = ill".  The trigger for this is "is_ill = yes", and not "trait = ill".  As such, this encompasses a lot of things, such as pneumonic (see "is_illness = yes" for a list of traits that are considered normal illness).  Therefore in order to match the trigger I changed it so that instead of removing just the "ill" trait it actually cures all normal illness.  Since this is a Druid doing the healing with magic that is presumably intended.

However, I believe that removes the need for a lot of unnecessary druid actions, such as druid.106 to remove pneumonic, or druid.108 to remove syphilitic.  This needs to be tested though.  For example I have seen that even though the "Cast Heal" action should do "cure_illness = yes" it did not in fact remove Lover's Pox or Great Pox (when it should since at least syphilitic is considered "is_illness = yes").

**Comment by TerryDuke** [comment]
Proposed fix in Pull Request #107

**Comment by rquinio** [comment]
I've seen this reported on the forums !

With Reaper's Due the court druid and court physician healing mechanics seem a bit redundant , but not exactly sure what to do.

**Comment by TerryDuke** [comment]
See my comments in PR #107

**Comment by rquinio** [comment]
Should be fixed ! I've also made the event only occur without Reaper's Due DLC.
