### ISSUE TITLE
Casting Heal (or Druid healing) doesn't cure Lover's Pox

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#108]
**Repro Steps**
1. Have a character afflicted with Lover's Pox (which is described as Herpes in the vanilla game comments).
2. Cast Heal on them.

**Expected**
That the lovers_pox trait be removed, since the description of Heal mentions that it cures illness.  It's also listed as an item in the list of triggers for "can_be_healed_by_magic_trigger".

**Actual**
The character still has Lover's Pox.

**Notes**
I believe this is caused because Lover's Pox does not have the characteristic "is_illness = yes".  It probably should, since it is a disease as per "has_disease_trigger" and "has_minor_disease_trigger" in the vanilla game, and one would describe it as an illness.  Regardless, this means that "cure_illness = yes" doesn't remove it, and hence as such just including "cure_illness = yes" in the game effects for casting Heal does not remove Lover's Pox.

**Comment by rquinio** [comment]
I wasn't sure about the impacts of adding is_illness = yes (could break balance of some vanilla events), so I've added the trait in mod healing conditions/effects instead.
