### ISSUE TITLE
Dezmod's Bloodline

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#114]
Radovid The Stern seems to have both Dezmod's bloodline and Radovid's bloodline.

**Comment by rquinio** [comment]
Yes, the reason is that Dezmod blood isn't patrilineal, otherwise Queen Bienvenu would break the line.
So through King Vestibor the Proud, whose mother was from Dezmoden dynasty, all Radovids get Dezmod blood.

**Comment by ajjr1996** [comment]
Dang I see what you mean now, that sucks kind of, it makes the world flooded with the trait and makes it a little less unique. I can't really find a work around though.

**Comment by ajjr1996** [comment]
I got an idea, could we do like what the Cintran dynasty did? Calanthe is in a matrilineal marriage and their bloodline still passes to her descendants. This would probably be the best work around.

**Comment by ajjr1996** [comment]
Ugh... I've tried copying everything from Calanthe's history and applying it to Bienvenu to make it matrilineal but I couldn't make it work to my knowledge. There has to be a way though.

**Comment by rquinio** [comment]
The problem was that Medell was born outside of marriage, so matrilineal status didn't show, and was considered a bastard for the bloodline I guess. I fixed it by adding the father (Hugo of Rivia).
