### ISSUE TITLE
Rulers can't appoint court chaplains

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#117]
Melitele rulers aren't able to recruit court chaplains, I'm not sure which other religions though.

**Comment by ajjr1996** [comment]
It's a strange issue, might take some looking into.

**Comment by rquinio** [comment]
Yeah it has been reported on Steam as well, could be related to bad merges of can_be_spiritiual_trigger trigger or investiture succession laws maybe ?

**Comment by rquinio** [comment]
Note: not specific to Melitele, also happens for Nilfgaard.

**Comment by rquinio** [comment]
Fixed
