### ISSUE TITLE
Wrong governments for mage/wilderness

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#119]
Pogroms are making a province tribal.

**Comment by ajjr1996** [comment]
Actually, I'm not sure what caused it to become tribal! Sorry about that!

**Comment by ajjr1996** [comment]
![20190110073853_1](https://user-images.githubusercontent.com/16552034/50972023-1cffcc80-14ab-11e9-9121-9123b7ad2926.jpg)

**Comment by ajjr1996** [comment]
Oh boy, yeah the wilderness mage tower mechanic is bugged really badly, it needs some major work. I'll keep trying to show you any bugs i find i'll load pictures.

**Comment by ajjr1996** [comment]
![20190110074657_1](https://user-images.githubusercontent.com/16552034/50972309-eecebc80-14ab-11e9-8388-69faded9cf99.jpg)

**Comment by rquinio** [comment]
I've seen some single counties becoming nomadic (not specific to wilderness/mage towers), not sure what is causing this - a faction ? a decision ?

**Comment by rquinio** [comment]
I've seen some single counties becoming nomadic (not specific to wilderness/mage towers), not sure what is causing this - a faction ? a decision ?

Btw make sure to activate game.log logging (-debugscripts launch option) and once you notice something weird, you may find more info in there to understand what happened. In particular anything related to mage towers or wilderness generates a log.

**Comment by ajjr1996** [comment]
For sure I’ll be sure to upload it and look through it myself.

**Comment by ajjr1996** [comment]
Adventurers seem to be attacking wilderness. Also, the court of Wilderness is huge, I wonder if there's a way to make people not want to go there.

**Comment by ajjr1996** [comment]
Wilderness is having uprisings also, making the province switch to nomadic.

**Comment by rquinio** [comment]
This should now be fixed, was due to nomad agitation event.
