### ISSUE TITLE
Many leaders adopting druidic faith

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#123]
The druidic faith seems to be adopted very regularly by rulers since it's appearing in their capital. It's kind of lore-breaking. I'm not sure what do do about it though, what do you think?

**Comment by rquinio** [comment]
The damand religious conversion diploaction is disabled, so not sure how they manage to convert (religion of province ? )

**Comment by ajjr1996** [comment]
Yeah it's from the druidic faith kind of just popping up in certain provinces and then the rulers seem to often adopt the faith. I think it'd be a little bit more lore friendly if there wasn't druidic kings and whatnot, the religion actually really takes hold in the later game. I had one game I left on observe and eventually 3 of the northen kings were druidic and giving vassals out to druidic lords. It's just kind of lore-breaking.

**Comment by rquinio** [comment]
I've reduced the ai_chances of the event to convert when a druid is at court, and generally the probabilities of a few druid events.
