### ISSUE TITLE
Dezmoden dynasty history adjustment

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#125]
The Dezmoden dynasty has a little sub-branch in Anchor that doesn't inherit the bloodline, I'm wondering if we should maybe remove these characters and give the duchy to someone else. This would make it a lot cooler for if Foltest gets assassinated before he can legitimize his kids too, causing the kingdom to separate instead of pass to this random sub-branch that technically doesn't exist in lore.

**Comment by ajjr1996** [comment]
![20190116070441_1](https://user-images.githubusercontent.com/16552034/51251004-d6541b80-195d-11e9-8453-894842264133.jpg)

**Comment by ajjr1996** [comment]
[House Dezmoden tweaks, d_Anchor history tweaked.zip](https://github.com/JonStryker/Witcher/files/2775328/House.Dezmoden.tweaks.d_Anchor.history.tweaked.zip)

**Comment by JonStryker** [comment]
I put those other Dezmoden's there for a reason back then. But I understand why you changed it.

**Comment by rquinio** [comment]
Some work on #51 / #144 will need to be done before we release, otherwise it'll make Foltest guaranteed game over.

**Comment by ajjr1996** [comment]
Who were the other Dezmodens if you don't mind me asking? I've never heard about them in the lore so far. But I still need to read the books.

**Comment by JonStryker** [comment]
The Dezmod dynasty is supposedly vast. So I added some very distant branch of the family that is not ni the line of succession. Non-canon though. 
But there is Jurkast (from Gra Wyobraźni, semi-canon), who is currently missing: https://witcher.fandom.com/wiki/Jurkast
