### ISSUE TITLE
Redanian and Kaedweni history tweaks

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#127]
[Redanian history tweaks.zip](https://github.com/JonStryker/Witcher/files/2775335/Redanian.history.tweaks.zip)

**Comment by ajjr1996** [comment]
Edited the Royal family and a couple holdings.

**Comment by rquinio** [comment]
Some work on #51 / #144 will need to be done before we release, otherwise it'll make Foltest guaranteed game over.
