### ISSUE TITLE
AOK events don't fire after resigning

### ISSUE THREAD

**Issue by rquinio** [JonStryker/Witcher#50]
Events are currently fired from history files, which don't execute if you resign/play.
Might be a vanilla bug, but in any case would seem more robust to fire events from an on_startup on_action, with a date & characer ID trigger and maybe has_game_started=no check, to avoid firing from saves.

**Comment by TMLCJLK** [comment]
This is actually a vanilla bug. The GoT mod was facing this problem too. I’m not sure if they fixed it at this new version. It is worth checking.

**Comment by rquinio** [comment]
This seems fixed in vanilla patch 3.0
