### ISSUE TITLE
Wilderness is employing mages and giving them land, as well as participating in defensive pacts.

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#65]

**Comment by rquinio** [comment]
Isn't that the unoccupied mage towers ?

**Comment by ajjr1996** [comment]
And Loc Muinne

**Comment by ajjr1996** [comment]
Maybe we should just give Loc Muinne back to the elves and give it about 4 or 5 building slots and have none built because the province was sacked by the humans.

**Comment by ajjr1996** [comment]
Or add a colonize event maybe? But yes, I've been testing extensively and it looks like the wilderness granting lands to mages is a huge bug either that or the assignment of a mage to a tower isn't working properly

**Comment by ajjr1996** [comment]
Wilderness is also entering into defensive pacts.

**Comment by rquinio** [comment]
Should be fixed !
