### ISSUE TITLE
Cure Infertility Ambition not working with Fertile Trait

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#74]
Just started playing as Duchess Francesca of Dol Blathanna, and loving it! Noticing some minor issues though.

**Repro**

1. Start a new game as Duchess Francesca of Dol Blathanna.
2. Notice that she has the Fertile trait.
3. In the character viewer select an Ambition, and look at "Cure infertility".  Notice that success condition says "Has the trait 'Fertile'".
4. Select "Cure infertility" as ambition.

**Expected**
I would have expected several things:

- That I should _not_ be able to select "Cure infertility" as an ambition.
- That as soon as I select it then I achieve that ambition.
- That the Success Condition correctly reflect what is actually needed to achieve this ambition.

**Actual**
Once selected, nothing happens, and you're stuck with that Ambition for a while.  There doesn't appear to be any way to achieve it with Francesca.

**Note**
I suspect what's happening is that the game is checking whether I can have kids.  I cannot in fact have kids since I'm a sorceress and my net fertility is roughly -1000 (from -1000 for Elf trait, +1000 for Fertile trait, and -1000 for Sorcerer trait).

I know only a little about modding, so I don't know if the "Success Condition" and "Success Effect" are auto-generated based on the underlying scripts... if so that might limit what we can do.  Also, I notice that there is no "Success Effect" for picking this Ambition.

![bug01-fertile](https://user-images.githubusercontent.com/39809872/40805340-f084f69a-64eb-11e8-8cf4-7f81f2a4d61b.png)

**Comment by rquinio** [comment]
Actually elven mages are tricky because there are 2 traits involved:
- fertile_sorcerer (to counteract the sorcerer trait malus) => The cure infertility ambition is about removing that one
- fertile_nonhuman (to counteract the elf_race trait malus) => it's automatically assigned to elves between between ~50 and ~250 years old.

Seems the description/naming of trait and/or ambition should be improved somehow to make things clearer ?

**Comment by TerryDuke** [comment]
Thanks for the explanation.

I might have misunderstood something.  Is there a way for sorcerers to become fertile?  I haven't seen that.  If there is then it starts to make sense... the Ambition would then be about trying to get the "fertile_sorcerer" trait.

Perhaps to clear up this confusion we could change the name of the traits as follows:

fertile_nonhuman : "Fertile Elf" (instead of just "Fertile")
fertile_sorcerer: "Fertile Sorcerer" (instead of whatever it's called now)

Then if I understand correctly the "Success Condition" would change to "Has the trait 'Fertile Sorcerer'", which would make it clear exactly what needs to be done.  Would this work?

**Comment by rquinio** [comment]
Perfect thanks!
