### ISSUE TITLE
No Descriptive Text for Sorceress Minor Title

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#75]
**Repro Steps**

1. Start a new game. It shouldn't matter as who.  I started as Duchess Francesca.
2. Go to the Councilors view, then the "Minor Titles" tab.
3. Hover over the "Sorceress" minor title.

**Expected**
I was expecting a short description of what this minor title means.

**Actual**
The viewer sees only "title_sorceress_desc".  Note that this does not happen for the "Sorcerer" minor title, where you correctly get a description.

**Notes**
The bug appears to be a missing letter "s" in title_sorceres_desc entry in the W-minor-titles.csv file.  I'll create and submit a Pull Request for this shortly.

**Pull Request**
#76 

![bug02-title_sorceress](https://user-images.githubusercontent.com/39809872/40808124-27062128-64f4-11e8-8675-0f34a51de7bf.png)

**Comment by TerryDuke** [comment]
Actually, I guess I don't have access rights to submit a new branch.  I do have a fix for this though, and I've verified it.  What is the process for creating a Pull Request?

**Comment by TerryDuke** [comment]
I created a cross-fork Pull Request in the meantime.  See #76

**Comment by rquinio** [comment]
Thanks, yes pull requests from fork are the way to go to contribute (at least at the beginning).

**Comment by TerryDuke** [comment]
Okay, I'll keep doing cross-fork Pull Requests for now then.
