### ISSUE TITLE
Endless notifications about founding of Hakland

### ISSUE THREAD

**Issue by rquinio** [JonStryker/Witcher#77]
This bug has been reported on steam by 2 persons and seems pretty annoying.
I don't more info though....

**Comment by terrydu** [comment]
The warning of warriors in the East, then the arrival of Haak, all worked correctly in my playthrough. Not sure if I ever got a notification about the founding of Hakland.  Not sure how best to reproduce this. We might need to look at the code.

**Comment by TerryDuke** [comment]
Right after posting that, I'm now able to reproduce it.  It actually happens when the nomads settle.  The realm of Hakland has existed for a while, but it seems at this point they change from no longer being nomads.

![hakland-settled](https://user-images.githubusercontent.com/39809872/41261395-7ff4b2d2-6da9-11e8-90fa-b4abc4ec9927.png)

I have a saved game file that I can share as well.

**Comment by TerryDuke** [comment]
It seems that his government type doesn't change to Feudal.

The wording from the event ties back to this event notification:
```
# Informed about nomad settling as feudal
narrative_event = {
	id = HL.1
	title = EVTNAMEHL1
	desc = EVTDESCHL1
	
	picture = GFX_evt_steppe_mercenaries
	border = GFX_event_narrative_frame_diplomacy
	
	is_triggered_only = yes
	
	option = {
		name = EVTOPTA62911
	}
}
```

But I've noticed that the government type of Hakland doesn't change to Feudal.  Also, on the world map you can see that Hakland's seat of government keeps changing location.  So it appears that he keeps trying to settle, but doesn't become Feudal (or maybe something sets him back), and hence he tries to go Feudal again and settle down, but doesn't become Feudal... and the loop repeats.

**Comment by rquinio** [comment]
Tried playing as Haakland after they win the nomad invasion - the settlement decision works and changes government.
I don't see the issue of capital changing location in my game, did 2.8.3 fix anything ?

**Comment by terrydu** [comment]
Btw, just to clarify, it happens to me when I do *not* play as Hakland.  In my case I'm playing as Duchess Francesca.  I don't know what it's like if you actually play as Hakland.  Either way, hopefully the saved game file will help figure out the specific repro steps.

**Comment by rquinio** [comment]
Thanks for the save, I was able to narrowed it down: it was a bad merge with vanilla file change of government was only happening when ai=no !
