### ISSUE TITLE
Minor grammar issues on Loading Tips

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#78]
**Repro Steps**

1. Load the game.
2. While it's doing so read the loading tips.
3. You might have to try multiple times until you see the ones in question.

**Actual**
The following are some of the loading tips that get displayed:
- "Even if you have multiple swords, in duel you can use only one or with Ambidextrous trait - two swords."
- "Artifacts and other items of value are not passed along the titles but within dynasty instead."
- "Sorcerers can hold magical tower holdings, which have special building tree that improves the sorcerer abilities."

**Expected**
This is pretty minor, but the sentences read a bit odd.  Here are some suggestions, though I'm open to feedback (I'm not an English major!):
- "in duel you can..." should be "in a duel you can..."
- "but within dynasty" should instead be "but within the dynasty" (also matches "along _the_ titles" earlier in the sentence).
- "which have special building tree" should instead be "which have a special building tree".
- "that improves the sorcerer abilities" should instead be "that improves their sorcerer abilities", since it's improving the Sorcerers (plural) mentioned as the first subject in this sentence.

![bug11-bad-grammar](https://user-images.githubusercontent.com/39809872/40869874-0a5760a2-65f1-11e8-9462-880dec9dffd2.png)

**Comment by rquinio** [comment]
Thanks, for minor/localization bugfixes don't worry too much about opening and describing the issue in detail, feel free to pull request directly.
