### ISSUE TITLE
Off-Hand Comment in an Event Mentions Europe

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#81]
**Repro Steps**
Not sure.  This was reported from Reddit.  See https://www.reddit.com/r/CrusaderKings/comments/8nq4uy/what_is_europe_i_bet_it_must_be_purified_with/

**Expected**
That this game doesn't have mention of Europe unless there is a strong canon reason.

**Actual**
An off-hand event, which I have not found in our Witcher mod code (and hence I'm assuming comes from Vanilla CK2), mentions Europe in passing.

**Note**
As a suggestion, perhaps this text could be changed to something like "who has served in most of the courts of the Northern Kingdoms"

![bug12-what-is-europe](https://user-images.githubusercontent.com/39809872/40870217-e42876c0-65f8-11e8-9b41-358d4e698940.jpg)

**Comment by rquinio** [comment]
+1 best is to keep the event and override the localization key in 00_W_vanilla_overrides.csv
There are so many events in vanilla that these anachronisms are hard to detect.
