### ISSUE TITLE
Hovering over a religious building flickers between names

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#86]
**Repro**

- Do *not* own Monks and Mystics DLC (I don't think this is related though).
- Start a game, for example as Duchess Francesca.
- Click on her home county of Casnewydd
- Hover over the red bar showing the levy.

**Actual**
It flickers really fast between "Temple Walls I", "Church Walls I", and "Mosque Walls I".  Other religious building names likewise flip between the different religious group names.

**Expected**
That it would show me "Temple Walls I", since in this case it's for the Temple of Shaentmorc.

**Note**
Looking through the code I see tp_town_1 that seems most appropriate.  It's defined in multiple places:
- 00_buildings.txt, where it defines the gold cost, build time, name, and so on, for a temple town.
- v2_82.csv, where it's defined as "tp_town_1;[Root.Holder.GetHouseOfWorshipCap] Town;"

Likewise, tp_town_1_desc (if you hover over the building improvement itself), which also has this problem, is defined in:
- v1_09.csv, where it's defined as "tp_town_1_desc;This small village of faithful peasants has formed around the [Root.Holder.GetHouseOfWorship].;"

So the problem appears to be related to calling the Root.Holder.GetHouseOfWorshipCap function (or Root.Holder.GetHouseOfWorship function).

The GetHouseOfWorshipCap function is defined in 00_customizable_localisation.txt, where it has a bunch of entries for each religion_group such as this:

```
defined_text = {
	name = GetHouseOfWorshipCap # Returns a suitable name for the house of worship of your religion (WIP)

	text = {
		localisation_key = string_Church
		trigger = { religion_group = christian }
	}
```

The variable "string_Church" is defined in v2_82.csv as ```string_Church;Church;```, which seems fine.

If we instead look at GetHouseOfWorship then it looks similar:

```defined_text = {
	name = GetHouseOfWorship # Returns a suitable name for the house of worship of your religion (WIP)

	text = {
		localisation_key = GetHouseOfWorship_Christian
		trigger = { religion_group = christian }
	}
```

That in turn is defined in MonksAndMystics.csv as the following (which looks correct):
```GetHouseOfWorship_Christian;church;```

Note that I don't own the Monks and Mystics DLC, but since it affects both GetHouseOfWorship and GerHouseofWorshipCap I don't think that matters.

So that seems to imply that either:
- religion_group keeps changing, which is why GetHouseOfWorship keeps returning a different value.
- Root.Holder keeps changing, which is why when GetHouseOfWorship is invoked it returns a different value.

Can anyone that *does* have Monks and Mystics confirm whether they see this problem? I don't think that's the cause to be honest, since I don't have this problem in vanilla CK2.

![bug05_church-walls](https://user-images.githubusercontent.com/39809872/40879792-863aad32-6673-11e8-87e7-ab1b1263f4ae.png)
![bug05_temple_x2](https://user-images.githubusercontent.com/39809872/40879793-88dffc86-6673-11e8-8c5e-a2c1a9a89672.png)
![bug05-mosque](https://user-images.githubusercontent.com/39809872/40879794-8c31617c-6673-11e8-9598-df3927b6e7eb.png)

**Comment by rquinio** [comment]
I reproduce it with Monks and Mystics DLC as well.
Since GetHouseOfWorship has no resulting value (none of religion groups match) I think it picks up a random one each time or something like that
Solution could be to copy the file 00_customizable_localisation.txt in the mod and adapt it for the religion groups ?

**Comment by TerryDuke** [comment]
Ah, I was going to ask you for a crash course or cheat sheet on how we modded religions.  I had assumed that we had adapted the existing ones, something like Christian -> Freya, Jewish -> Dana Méadbh, and so on.

Based on what you've said though, we've created completely new religions that don't refer to the existing ones?  If so, then Yes I think we just need to add the Witcher religions to those two methods.

**Comment by rquinio** [comment]
Exactly, the religion groups are the root blocks in the file https://github.com/JonStryker/Witcher/blob/master/MOD/Witcher/common/religions/W_religions.txt (northern_religions, elven_religions, ...)

**Comment by TerryDuke** [comment]
Got it, thanks.

I'm trying to add some logging, to get a peek at what the values are when GetHouseOfWorship is called.  I see elsewhere code to this effect: ```log = "(AoK) claim_lormark on_success_title"```. 

How does that work?  Does it write a log message to one of the existing log files?  Or do I need to run a command to see the value of a variable named "log" in the command-prompt in the game?

When I add a similar log statement in GetHouseOfWorship (in 00_customizable_localisation.txt), such as ```log = "- This: [This.GetName][This.GetBestName]"```, I get the following error message in \Documents\Paradox Interactive\Crusader Kings II\logs\errors.log:

```[persistent.cpp:40]: Error: "Unexpected token: log, near line: 2401" in file: "localisation/customizable_localisation/00_customizable_localisation.txt"```

Any idea as to how I would look at values in the script, either by logging or otherwise?

**Comment by rquinio** [comment]
log effect logs stuff to game.log file (see https://ck2.paradoxwikis.com/Troubleshooting#Log_files you may need -debugscripts launch option)
Effects won't work inside defined_text. What you could do is use the localized output itself to display what you want to see (haven't tested):

```
defined_text = {
  name = GetHouseOfWorship
  fallback_text = {
     localisation_key = debug_key
  }
}
```
```
debug_key;;[This.Religion.GetGroupName];;;;;;;;;;;;;x
```

**Comment by rquinio** [comment]
Great, we can refine some naming in the future if needed.
