### ISSUE TITLE
Witcher Font: & symbol is as designed?

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#93]
The new submod is very cool.  Didn't realize that was possible!  Still not sure if I like it or not, to be honest, but I'm trying it out.  Is that the font used for the title screen?

Anyhow, the question:  Is the "&" symbol for "Lyria & Rivia" as designed, or is that a placeholder?

(Btw what is the best way to contact you directly, so that I don't need to ask questions via opening Issues?  You can reach me at _redacted_.)

![question1_front_and-sign](https://user-images.githubusercontent.com/39809872/41231343-cc7349c4-6d50-11e8-91ef-7e6ad46fa2ac.png)

**Comment by rquinio** [comment]
Thanks, yeah I made it optional as I know some players will prefer the vanilla one.
The & is like that in the font, you can test it live at http://www.fontspace.com/category/the-witcher
(I've just sent you an invitation to witcherkings slack channel, should be easier !)

**Comment by rquinio** [comment]
Also try out the characters "{}()" for a surprise :p

**Comment by TerryDuke** [comment]
Haha, neat.

Let's close this Issue then, since it's as designed.
