### ISSUE TITLE
Compatibility with 2.8.3

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#95]
**Repro Steps**
1. Make sure your CK2 game is patched to version 2.8.3 (the one that mentions GDPR and privacy).
2. Select the Witcher Kings mod in your list of DLCs.
3. Start the game.
4. The progress bar will finish loading all the flags, graphics, etc...

**Actual**
The game crashes with the following error in Witcher/logs/exceptions.log:
```
######## EXCEPTION: 0xC0000005 at address: 0x006AC0C1: ACCESS VIOLATION  read attempt to address 0x00000000 
Version: Unknown Version
06/12/18 10:47:55
```
(It's the same error each time)

**Expected**
That it load correctly.

**Note**
If you don't enable the mod then it works fine.  If you load another mod then it works fine.  So it's just our mod.

This happens with or without the Jade Dragon DLC, and with or without the new Witcher Fonts sub-mod.

**Comment by rquinio** [comment]
Fixed !

**Comment by TerryDuke** [comment]
I tried this out and it's working again :-)
