### ISSUE TITLE
Player is Witcher in Event Notification

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#97]
**Repro Steps**
To be honest I'm not completely sure of how to reproduce this. You need some monsters to be in your demense, but I do not recall if I already had a Witcher in my court (I think I did), and whether I had sent soldiers or the Witcher (I might have sent the soldiers).

**Expected**
That after the monsters are cleared out I see a notification event informing me of this, with the text that is "signed" by the Witcher, and with the Witcher's portrait.

**Actual**
The message is to myself (with my full title) and from myself.  In fact it is signed "Witcher Francesca verch Diared Findabair". Also the portrait is blank.

This has happened a couple of times now, but as mentioned I don't recall the setup and so we still need better repro steps.

**Notes**
The description text is:
```EVTDESCmonster.3;Honoured [Root.GetTitledName],\n\nI have taken care of the drowners as you requested.\n\nWitcher [FromFrom.GetFullName];;;;;;;;;;;;;x```

This is used in the following event:
```
# Witcher does its craft
letter_event = {
	id = monster.3
	desc = EVTDESCmonster.3
	
	hide_from = yes
	is_triggered_only = yes
	
	option = {
		name = EVTOPTAmonster.3
		random_demesne_province = {
			limit = { has_province_modifier = drowners }
			remove_province_modifier = drowners
			add_province_modifier = { name = monster_purge duration = 360 hidden = yes }
		}
		wealth = -10
		FROM = { 
			wealth = 10
			add_character_modifier = { name = recent_witcher_work duration = 180 hidden = yes }
		}
	}
}
```

![bug19-witcher-is-empress](https://user-images.githubusercontent.com/39809872/41498818-64408072-7144-11e8-9a18-fb1fd4c6c12d.png)

**Comment by rquinio** [comment]
Fixed
