### ISSUE TITLE
"Prepare the bones/n"

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#98]
**Repro Steps**
1. Be a sorcerer ruler.
2. Choose the "Cure infertility" ambition.
3. Get the Mecopteran bones quest line.
4. Get the bones.

**Actual**
In the hover tooltip for the "Now to make the soup" option the text says "Prepare the bones/n".

**Expected**
That we don't see any "/n". In other words the tooltip hover text should just be "Prepare the bones".

**Note**
Perhaps it was meant to be "\n"?  Either way, what I'll do is just remove the "/n" since we don't need a newline in the hover tooltip.  The text is defined as ```use_bones;Prepare the bones/n;;;;;;;;;;;;;x```

![bug16-prepare-the-bones](https://user-images.githubusercontent.com/39809872/41498854-54cb4ec8-7145-11e8-933a-0685f497598a.png)

**Comment by TerryDuke** [comment]
See Pull Request #99 for a proposed fix.

**Comment by rquinio** [comment]
Btw I was thinking this could be an (alchemical) artifact.
